apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: devopsbeerer-frontoffice
data:
  config.json: >
    {
      "devopsbeerUrl": "https://api.devopsbeerer.local",
      "version": "v1.0.0",
      "environment": "polayground",
      "organizationName": "DevopsDays"
    }

  auth.json: >
    {
        "authority": "https://sso.devopsbeerer.local/realms/devopsbeerer",
        "redirectUrl": "https://app.devopsbeerer.local/callback",
        "postLogoutRedirectUri": "https://app.devopsbeerer.local:4200",
        "clientId": "devopsbeerer-frontoffice",
        "secureRoutes": [
            "https://api.devopsbeerer.local/"
        ]
    }
