apiVersion: v1
kind: Service
metadata:
  labels:
    app: devopsbeerer-frontoffice
  name: devopsbeerer-frontoffice
  namespace: devopsbeerer-frontoffice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: devopsbeerer-frontoffice